{{- if .Values.resources.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docspring-enterprise.name" . }}-postgres
  labels:
    app: {{ include "docspring-enterprise.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "docspring-enterprise.name" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "docspring-enterprise.name" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRES_USER
              value: {{ .Values.resources.postgres.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.resources.postgres.auth.password }}
            - name: POSTGRES_DB
              value: {{ .Values.resources.postgres.auth.database }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: {{ .Values.resources.postgres.resources.requests.memory }}
              cpu: {{ .Values.resources.postgres.resources.requests.cpu }}
{{- end }}
