# templates/redis-service.yaml
{{- if .Values.resources.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docspring-enterprise.name" . }}-redis
  labels:
    app: {{ include "docspring-enterprise.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ include "docspring-enterprise.name" . }}
    component: redis
{{- end }}
