apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docspring-enterprise.name" . }}-worker
  labels:
    app: {{ include "docspring-enterprise.name" . }}
spec:
  replicas: {{ .Values.worker.replicas }}
  strategy:
    type: {{ .Values.deploymentStrategy }}
  selector:
    matchLabels:
      app: {{ include "docspring-enterprise.name" . }}
      component: worker
  template:
    metadata:
      labels:
        app: {{ include "docspring-enterprise.name" . }}
        component: worker
    spec:
      imagePullSecrets:
        - name: {{ index .Values.image.pullSecrets 0 "name" }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          env:
            {{- include "docspring-enterprise.sharedEnvVars" . | nindent 12 }}
            {{- range $key, $value := .Values.worker.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            limits:
              memory: {{ .Values.worker.resources.limits.memory }}
              cpu: {{ .Values.worker.resources.limits.cpu }}
            requests:
              memory: {{ .Values.worker.resources.requests.memory }}
              cpu: {{ .Values.worker.resources.requests.cpu }}
          securityContext:
            privileged: {{ .Values.worker.securityContext.privileged }}
